apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      imagePullSecrets:
      - name: {{ template "fullname" . }}-registry
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 8000
        env:
        - name: VICTOROPS_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: victorops.account.id
        - name: VICTOROPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: victorops.api.key
