image: registry.cnct.io/venezia/helm-registry-agent:v0.7.4-helm_2.6

variables:
  IMAGE_DEVL_URI: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
  IMAGE_PROD_URI: $CI_REGISTRY_IMAGE:latest
  KUBECONFIG: /root/.kube/config
  APP: cyklops-events

stages:
  - package
  - test
  - staging
  - production

package:
  stage: package
  only:
    - branches
    - master
  script:
  - echo package chart

test:
  stage: test
  script:
  - helm lint ${APP}

deploy_staging:
  stage: staging
  environment:
    name: staging
  before_script:
  - mkdir /root/.kube
  - echo ${ENV_KUBECONFIG}
  - echo ${ENV_KUBECONFIG} | base64 -d > ${KUBECONFIG}
  - helm init --client-only
  script:
  - helm version
  - helm install --namespace ${APP}-${CI_ENVIRONMENT_SLUG} ${APP} --set registry.dockerConfig=$REGISTRY_DOCKERCFG --debug

deploy_production:
  stage: production
  environment:
    name: production
  when: manual
  script:
  - echo TODO add manual approval deploy $IMAGE_PROD_URI to producrtion environment
  - echo DEBUG CI_ENVIRONMENT_NAME=$CI_ENVIRONMENT_NAME
  - echo DEBUG CI_ENVIRONMENT_SLUG=$CI_ENVIRONMENT_SLUG
