image: quay.io/samsung_cnct/helm-registry-agent:v0.7.4-helm_2.6

variables:
  KUBECONFIG: /root/.kube/config
  APP_NAME: cyklops-events
  CHART_NAME: cyklops-events-chart
  CHART_REGISTRY_URI: ${REGISTRY_HOST}/${REGISTRY_ORG}/${CHART_NAME}

stages:
  - build
  - test
  - publish
  - staging
  - production

build-branch:
  stage: build
  only:
    - branches
    - master
  artifacts:
    paths:
    - ./${APP_NAME}/Chart.yaml
    expire_in: 1 week
  script:
  - export CHART_REL=$(git rev-parse --short HEAD)
  - export CHART_VER=0.1.1-${CI_COMMIT_REF_SLUG}
  - ./build.sh

build-tags:
  stage: build
  only:
    - tags
  artifacts:
    paths:
    - ./*/Chart.yaml
    expire_in: 1 week
  script:
  - export CHART_VER=${CI_COMMIT_TAG}
  - export CHART_REL=0
  - ./build.sh

test:
  stage: test
  script:
  - cat ${APP_NAME}/Chart.yaml
  - helm lint ${APP_NAME}

publish-alpha:
  stage: publish
  only:
    - branches
    - master
  script:
  - export CHART_REGISTRY_CHANNEL=alpha
  - ./publish.sh

publish-stable:
  stage: publish
  only:
    - tags 
  script:
  - export CHART_REGISTRY_CHANNEL=stable
  - ./publish.sh

deploy-staging:
  stage: staging
  environment:
    name: staging
  script:
  - export APP_ENV=staging
  - ./deploy.sh 

deploy-production:
  stage: production
  environment:
    name: production
  when: manual
  script:
  - export APP_ENV=production
  - ./deploy.sh 
