version: "2.1"

services:
   helm-reg:
      image: quay.io/samsung_cnct/helm-registry-agent:v0.7.4-helm_2.6
      working_dir: /app/chart-cyklops-events
      env_file: .env
      volumes:
         - ${PWD}:/app/chart-cyklops-events
         - ${KUBECONFIG}:/root/.kube/config

   build:
      extends:
         service: helm-reg
      command: ["./build.sh"]

   test:
      extends:
         service: helm-reg
      working_dir: /app/chart-cyklops-events/cyklops-events
      command: ["helm", "lint"]

   publish:
      extends:
         service: helm-reg
      command: ["./publish.sh"]
         
   deploy:
      extends:
         service: helm-reg
      command: ["./deploy.sh"]
