#!/usr/bin/env bash

APP_NAME=cyklops-events

REGISTRY_HOST=quay.io
REGISTRY_ORG=samsung_cnct
REGISTRY_USERNAME=${REGISTRY_USERNAME:-quay-repo-robot}
REGISTRY_PASSWORD=${REGISTRY_PASSWORD:-quay-repo-robot-token}

CHART_NAME=${APP_NAME}-chart
CHART_REGISTRY_URI=${REGISTRY_HOST}/${REGISTRY_ORG}/${CHART_NAME}
CHART_REGISTRY_CHANNEL=${CHART_REGISTRY_CHANNEL:-alpha}

cd ${APP_NAME}
helm registry login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
helm registry push ${CHART_REGISTRY_URI} -c ${CHART_REGISTRY_CHANNEL}
